language: php
sudo: required
dist: trusty

jobs:
  include:
    - php: 7.2
      install:
        - pecl install grpc || echo 'Failed to install grpc'
        - pecl install stackdriver_debugger-alpha || echo 'Failed to install stackdriver_debugger';
        - composer self-update
        - composer install
        - ./dev/google-cloud credentials;

    # - php: 7.1
    #   install:
    #     - pecl install grpc || echo 'Failed to install grpc'
    #     - pecl install stackdriver_debugger-alpha || echo 'Failed to install stackdriver_debugger';
    #     - composer self-update
    #     - composer install
    #     - ./dev/google-cloud credentials;

    # - php: 7.0
    #   install:
    #     - pecl install grpc || echo 'Failed to install grpc'
    #     - pecl install stackdriver_debugger-alpha || echo 'Failed to install stackdriver_debugger';
    #     - composer self-update
    #     - composer install
    #     - ./dev/google-cloud credentials;

    - php: 5.6.25
      install:
        - pecl install grpc || echo 'Failed to install grpc'
        - composer self-update
        - composer install
        - ./dev/google-cloud credentials;

    # - php: 5.5.38
    #   install:
    #     - pecl install grpc || echo 'Failed to install grpc'
    #     - composer self-update
    #     - composer install
    #     - ./dev/google-cloud credentials;

    - php: hhvm-3.24
      install:
        - composer self-update
        - composer install
        - ./dev/google-cloud credentials;
        - composer --no-interaction --dev remove google/protobuf google/gax google/proto-client;

    - stage: "Build Docs"
      php: 7.2
      install:
      - travis_retry composer install
      script:
      - ./dev/sh/build-docs

    - stage: "Push Docs"
      php: 7.2
      install:
      - travis_retry composer install
      script:
      - ./dev/sh/build-docs
      - ./dev/sh/push-docs $TRAVIS_BRANCH

    - stage: "Split Components"
      php: 7.2
      install:
      - travis_retry composer install
      script:
      - ./dev/sh/trigger-split
      notifications:
        email:
          recipients:
            - john@pedrie.com
          on_success: always
          on_failure: always

stages:
  - test
  - name: "Build Docs"
    if: ((type = pull_request) OR (branch != master)) AND !(tag IS present)
  - name: "Push Docs"
    if: ((type != pull_request) AND (branch = master)) OR (tag IS present)
  - name: "Split Components"
    if: (tag IS present)

env:
  global:
    - GOOGLE_CLOUD_PHP_TESTS_KEY_PATH=$TRAVIS_BUILD_DIR/keys/GOOGLE_CLOUD_PHP_TESTS.json
    - GOOGLE_CLOUD_PHP_TESTS_WHITELIST_KEY_PATH=$TRAVIS_BUILD_DIR/keys/GOOGLE_CLOUD_PHP_TESTS_WHITELIST.json

script:
- ./dev/sh/tests

after_success:
- if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then bash <(curl -s https://codecov.io/bash); fi
