#!/bin/bash

set -ev

function buildDocs () {
  if [ -z "$tagName" ]; then
    ./dev/google-cloud docs
  else
    ./dev/google-cloud docs -r
  fi
}


buildDocs

if [ "${GITHUB_REF##*/}" == "master" ]; then
  echo "hello"
fi
