name: Generate Documentation
on:
    push:
        branches:
            - master
        tags:
            - "*"

jobs:
    docs:
        name: "Generate Project Documentation"
        runs-on: ubuntu-16.04
        steps:
        - uses: olegtarasov/get-tag@v2
          id: tagName
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Dependencies
          uses: nick-invision/retry@v1
          with:
            timeout_minutes: 10
            max_attempts: 3
            command: composer update
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'
            ini-values: memory_limit=2048M
        - name: Build Documentation
          run: './dev/sh/build-docs'
          with:
            tagName: ${{ steps.tagName.outputs.tag }}

        # - name: Deploy 🚀
        #   uses: JamesIves/github-pages-deploy-action@releases/v3
        #   with:
        #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        #     BRANCH: gh-pages
        #     FOLDER: .docs
