on:
  push:
    branches:
      - master
    paths:
      - 'PubSub/**'
  pull_request:
    paths:
      - 'PubSub/**'
name: Run PubSub System Tests With Emulator
jobs:
  php-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: apk add expect && unbuffer ./start-pubsub-emulator.sh

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          tools: pecl
          extensions: bcmath, grpc

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-suggest -d PubSub/

      - name: Run system tests
        run: |
          PubSub/vendor/bin/phpunit -c PubSub/phpunit-system.xml.dist
        env:
          PUBSUB_EMULATOR_HOST: localhost:8085
